// <auto-generated />
using System;
using Gdc.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gdc.Infrastructure.Migrations
{
    [DbContext(typeof(GdcDbContext))]
    [Migration("20260610194623_DgcDescuentoMatriz")]
    partial class DgcDescuentoMatriz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dgc")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.Comparendo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Documento")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("documento");

                    b.Property<string>("DpReferencia")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dp_referencia");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<string>("EstadoPago")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado_pago");

                    b.Property<DateOnly?>("FechaComparendo")
                        .HasColumnType("date")
                        .HasColumnName("fecha_comparendo");

                    b.Property<DateOnly?>("FechaNotificacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_notificacion");

                    b.Property<string>("Fuente")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("fuente");

                    b.Property<string>("InfraccionCodigo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("infraccion_codigo");

                    b.Property<string>("InfractorNombre")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("infractor_nombre");

                    b.Property<string>("NumeroComparendo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("numero_comparendo");

                    b.Property<bool>("PendienteContraventor")
                        .HasColumnType("boolean")
                        .HasColumnName("pendiente_contraventor");

                    b.Property<string>("Placa")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("placa");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SecretariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("secretaria_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalValor")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("total_valor");

                    b.Property<DateTimeOffset?>("UltimoIntentoAsociacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_intento_asociacion");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NumeroComparendo")
                        .IsUnique()
                        .HasDatabaseName("uq_comparendos_tenant_numero");

                    b.ToTable("comparendos", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.Contraventor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AsociacionAutomatica")
                        .HasColumnType("boolean")
                        .HasColumnName("asociacion_automatica");

                    b.Property<Guid>("ComparendoId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparendo_id");

                    b.Property<string>("Correo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("documento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nombre");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ComparendoId")
                        .IsUnique()
                        .HasDatabaseName("uq_contraventors_comparendo_id");

                    b.ToTable("contraventors", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.ContraventorJobConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cron_expression");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("WindowOrder")
                        .HasColumnType("integer")
                        .HasColumnName("window_order");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "WindowOrder")
                        .IsUnique()
                        .HasDatabaseName("uq_contraventor_job_configs_tenant_window");

                    b.ToTable("contraventor_job_configs", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.DescuentoMatriz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<int>("DiasDescuento")
                        .HasColumnType("integer")
                        .HasColumnName("dias_descuento");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid?>("SecretariaId")
                        .HasColumnType("uuid")
                        .HasColumnName("secretaria_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "SecretariaId")
                        .IsUnique()
                        .HasDatabaseName("uq_descuento_matrices_tenant_secretaria");

                    b.ToTable("descuento_matrices", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cc")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("cc");

                    b.Property<Guid>("ComparendoId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparendo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destino");

                    b.Property<string>("EstadoEntrega")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado_entrega");

                    b.Property<string>("HtmlEvidencia")
                        .HasColumnType("text")
                        .HasColumnName("html_evidencia");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("origen");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tipo_alerta");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ComparendoId")
                        .HasDatabaseName("ix_email_logs_comparendo_id");

                    b.ToTable("email_logs", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.OcrItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArchivoUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("archivo_uri");

                    b.Property<Guid?>("ComparendoId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparendo_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("OcrLoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ocr_lote_id");

                    b.Property<string>("OcrPayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ocr_payload_json");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("ComparendoId");

                    b.HasIndex("OcrLoteId")
                        .HasDatabaseName("ix_ocr_items_ocr_lote_id");

                    b.ToTable("ocr_items", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.OcrLote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("row_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("ocr_lotes", "dgc");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.Contraventor", b =>
                {
                    b.HasOne("Gdc.Modules.Dgc.Domain.Entities.Comparendo", "Comparendo")
                        .WithOne("Contraventor")
                        .HasForeignKey("Gdc.Modules.Dgc.Domain.Entities.Contraventor", "ComparendoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comparendo");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.EmailLog", b =>
                {
                    b.HasOne("Gdc.Modules.Dgc.Domain.Entities.Comparendo", "Comparendo")
                        .WithMany("EmailLogs")
                        .HasForeignKey("ComparendoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comparendo");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.OcrItem", b =>
                {
                    b.HasOne("Gdc.Modules.Dgc.Domain.Entities.Comparendo", "Comparendo")
                        .WithMany("OcrItems")
                        .HasForeignKey("ComparendoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Gdc.Modules.Dgc.Domain.Entities.OcrLote", "OcrLote")
                        .WithMany("Items")
                        .HasForeignKey("OcrLoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comparendo");

                    b.Navigation("OcrLote");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.Comparendo", b =>
                {
                    b.Navigation("Contraventor");

                    b.Navigation("EmailLogs");

                    b.Navigation("OcrItems");
                });

            modelBuilder.Entity("Gdc.Modules.Dgc.Domain.Entities.OcrLote", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
